# develop enviroment

steps:
  # Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'ops/Dockerfile', '-t', 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME', '.']
  
  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME']

  # Deploy to CloudRun
  - name: 'gcr.io/cloud-builders/gcloud-slim'
    args: 
    - 'run'
    - 'deploy'
    - '$REPO_NAME-$BRANCH_NAME'
    - '--region'
    - 'asia-southeast2'
    - '--platform'
    - 'managed'
    - '--image'
    - 'asia.gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME'
    - '--port'
    - '3000'
    - '--allow-unauthenticated'