name: ci-pipeline-staging

on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pull repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to SWR Huawei
        uses: docker/login-action@v1.14.1
        with:
          registry: swr.ap-southeast-3.myhuaweicloud.com
          username: ap-southeast-3@${{ secrets.HUAWEI_ACCESS_KEY }}
          password: ${{ secrets.HUAWEI_LOGIN_KEY }}

      - name: Build & push to SWR Huawei
        run: |
          short_git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker build -f ops/Dockerfile -t swr.ap-southeast-3.myhuaweicloud.com/cce-demo/category-api:$short_git_hash .
          docker push swr.ap-southeast-3.myhuaweicloud.com/cce-demo/category-api:$short_git_hash

  # trigger-deployment:
  #     runs-on: ubuntu-latest
  #     needs: build-dockerfile

  #     steps:
  #       - uses: actions/checkout@v3

  #       - name: pull & update config deployment
  #         run: |
  #           short_git_hash=$(git rev-parse --short "$GITHUB_SHA")
  #           git config --global user.email "dianraha11@gmail.com"
  #           git config --global user.name "huawei-auto-deploy"
  #           git clone https://${{ secrets.PERSONAL_TOKEN_DEPLOYMENT }}@github.com/sonarid/k8s-manifest.git
  #           cd k8s-manifest
  #           sed -i "s+category-api/repository-api.*+category-api/repository-api:staging-$short_git_hash+g" repository-api/staging/k8s/deployment.yaml
  #           git commit -am "Auto deploy: $short_git_hash - staging - repository-api"
  #           git push https://${{ secrets.PERSONAL_TOKEN_DEPLOYMENT }}@github.com/sonarid/k8s-manifest.git