name: ci-pipeline-staging

on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: pull repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to SWR Huawei
        uses: docker/login-action@v1.14.1
        with:
          registry: swr.ap-southeast-3.myhuaweicloud.com
          username: ap-southeast-3@${{ secrets.HUAWEI_ACCESS_KEY }}
          password: ${{ secrets.HUAWEI_LOGIN_KEY }}

      - name: Build & push to SWR Huawei
        run: |
          short_git_hash=$(git rev-parse --short "$GITHUB_SHA")
          docker build -f ops/Dockerfile -t swr.ap-southeast-3.myhuaweicloud.com/cce-demo/category-api:$short_git_hash .
          docker push swr.ap-southeast-3.myhuaweicloud.com/cce-demo/category-api:$short_git_hash

  trigger-deployment:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - uses: actions/checkout@v3

        - name: pull & update config deployment
          run: |
            short_git_hash=$(git rev-parse --short "$GITHUB_SHA")
            git config --global user.email "dianraha11@gmail.com"
            git config --global user.name "huawei-auto-deploy"
            git clone https://${{ secrets.PERSONAL_TOKEN_DEPLOYMENT }}@github.com/rahadiangg/service-deployment.git
            cd service-deployment
            sed -i "s+cce-demo/category-api.*+cce-demo/category-api:$short_git_hash+g" category-api/k8s/deployment.yaml
            git commit -am "Auto deploy: $short_git_hash"
            git push https://${{ secrets.PERSONAL_TOKEN_DEPLOYMENT }}@github.com/rahadiangg/service-deployment.git