name: pipeline-ci

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to SWR Huawei
        uses: docker/login-action@v1.14.1
        with:
          registry: swr.ap-southeast-3.myhuaweicloud.com
          username: ${{ secrets.HUAWEI_ACCESS_KEY }}
          password: ${{ secrets.HUAWEI_LOGIN_KEY }}

      - name: Build & push to SWR Huawei
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          file: ops/Dockerfile
          tags: sonar-test/category-api:develop

